---
- name: "DOCKER : copy .env files"
  template:
    src: "{{ item }}"
    dest: "files/env/{{ item | basename | regex_replace('.j2$','') }}"
    mode: '0644'
  with_fileglob:
    - ../templates/*.j2

- name: 'DOCKER : create volume'
  community.docker.docker_volume:
    name: volume_pihole
  become: true

- name: 'DOCKER : create containers'
  community.docker.docker_compose_v2:
    project_src: files/
    pull: always
#    recreate: always
  become: true

- name: 'DOCKER : remove unused images'
  community.docker.docker_prune:
    images: true
  become: true
